### ISSUE TITLE
Problems with xmpp (exceptions.TypeError: groupChat() got an unexpected keyword argument 'children')

### ISSUE THREAD

**Issue by c0r3dump3d** [desaster/kippo#175]
Hi, I try to use the xmpp kippo feature but when kippo try to send an event to the xmpp server Python exception occurs:

[kippo.core.ssh.HoneyPotSSHFactory] Log observer <bound method DBLogger.emit of <kippo.dblog.xmpp.DBLogger object at 0x28bee50>> failed.
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 725, in doRead
	    protocol.makeConnection(transport)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/protocol.py", line 462, in makeConnection
	    self.connectionMade()
	  File "/usr/local/src/kippo/kippo/core/ssh.py", line 137, in connectionMade
	    self.transport.sessionno)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 594, in write
	    msg(message, printed=1, isError=self.isError)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 284, in msg
	    self.observers[i](actualEventDict)
	  File "/usr/local/src/kippo/kippo/core/dblog.py", line 74, in emit
	    match.groups()[2], int(match.groups()[3]))
	  File "/usr/local/src/kippo/kippo/dblog/xmpp.py", line 117, in createSession
	    self.broadcast('createsession', ses)
	  File "/usr/local/src/kippo/kippo/dblog/xmpp.py", line 93, in broadcast
	    (self.signals[msgtype], self.muc.server) , msg)
	  File "/usr/local/src/kippo/kippo/dblog/xmpp.py", line 102, in report
	    self.muc.groupChat(to,  None, children=[body])
	exceptions.TypeError: groupChat() got an unexpected keyword argument 'children'

Thank you in advance.

**Comment by micheloosterhof** [comment]
Duplicate of https://github.com/desaster/kippo/issues/53
