### ISSUE TITLE
Unhandled python exception on "mv foo ~/bar"

### ISSUE THREAD

**Issue by neuschaefer** [desaster/kippo#178]
```
2015-02-25 04:11:34+0100 [SSHChannel session (0) on SSHService ssh-connection on HoneyPotTransport,21,<redacted>] CMD: mv ~/a ~/B
2015-02-25 04:11:34+0100 [SSHChannel session (0) on SSHService ssh-connection on HoneyPotTransport,21,<redacted>] Command found: mv ~/a ~/B
2015-02-25 04:11:34+0100 [SSHChannel session (0) on SSHService ssh-connection on HoneyPotTransport,21,<redacted>] Unhandled Error
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
        return self.currentContext().callWithContext(ctx, func, *args, **kw)
      File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
        return func(*args,**kw)
      File "/usr/lib/python2.7/dist-packages/twisted/conch/ssh/service.py", line 44, in packetReceived
        return f(packet)
      File "/usr/lib/python2.7/dist-packages/twisted/conch/ssh/connection.py", line 242, in ssh_CHANNEL_DATA
        log.callWithLogger(channel, channel.dataReceived, data)
    --- <exception caught here> ---
      File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 88, in callWithLogger
        return callWithContext({"system": lp}, func, *args, **kw)
      File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 73, in callWithContext
        return context.call({ILogContext: newCtx}, func, *args, **kw)
      File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
        return self.currentContext().callWithContext(ctx, func, *args, **kw)
      File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
        return func(*args,**kw)
      File "/usr/lib/python2.7/dist-packages/twisted/conch/ssh/session.py", line 107, in dataReceived
        self.client.transport.write(data)
      File "/usr/lib/python2.7/dist-packages/twisted/conch/ssh/session.py", line 158, in write
        self.proto.dataReceived(data)
      File "/usr/lib/python2.7/dist-packages/twisted/conch/insults/insults.py", line 431, in dataReceived
        self.terminalProtocol.keystrokeReceived(ch, None)
      File "/home/pot/kippo/kippo/core/protocol.py", line 189, in keystrokeReceived
        recvline.HistoricRecvLine.keystrokeReceived(self, keyID, modifier)
      File "/usr/lib/python2.7/dist-packages/twisted/conch/recvline.py", line 199, in keystrokeReceived
        m()
      File "/home/pot/kippo/kippo/core/protocol.py", line 206, in handle_RETURN
        return recvline.RecvLine.handle_RETURN(self)
      File "/usr/lib/python2.7/dist-packages/twisted/conch/recvline.py", line 257, in handle_RETURN
        self.lineReceived(line)
      File "/home/pot/kippo/kippo/core/protocol.py", line 108, in lineReceived
        self.cmdstack[-1].lineReceived(line)
      File "/home/pot/kippo/kippo/core/honeypot.py", line 68, in lineReceived
        self.runCommand()
      File "/home/pot/kippo/kippo/core/honeypot.py", line 125, in runCommand
        self.honeypot.call_command(cmdclass, *rargs)
      File "/home/pot/kippo/kippo/core/protocol.py", line 182, in call_command
        HoneyPotBaseProtocol.call_command(self, cmd, *args)
      File "/home/pot/kippo/kippo/core/protocol.py", line 117, in call_command
        obj.start()
      File "/home/pot/kippo/kippo/core/honeypot.py", line 26, in start
        self.call()
      File "/home/pot/kippo/kippo/commands/fs.py", line 180, in call
        if self.fs.is_dir(resolv(dest)):
      File "/home/pot/kippo/kippo/core/fs.py", line 172, in is_dir
        dir = self.get_path(os.path.dirname(path))
      File "/home/pot/kippo/kippo/core/fs.py", line 87, in get_path
        p = [x for x in p[A_CONTENTS] if x[A_NAME] == i][0]
    exceptions.IndexError: list index out of range
```

**Comment by neuschaefer** [comment]
The kippo version is 860224de3a.
