### ISSUE TITLE
Error if i start kippo

### ISSUE THREAD

**Issue by Luegenbaron** [desaster/kippo#192]
Hello 
When i start kippo in env than it print me the following:

(env)kippo@Honey:~/kippo$ twistd -n -y kippo.tac
Unhandled Error
Traceback (most recent call last):
  File "/home/kippo/env/local/lib/python2.7/site-packages/twisted/application/app.py", line 617, in run
    runApp(config)
  File "/home/kippo/env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/home/kippo/env/local/lib/python2.7/site-packages/twisted/application/app.py", line 348, in run
    self.application = self.createOrGetApplication()
  File "/home/kippo/env/local/lib/python2.7/site-packages/twisted/application/app.py", line 413, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/home/kippo/env/local/lib/python2.7/site-packages/twisted/application/app.py", line 424, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/home/kippo/env/local/lib/python2.7/site-packages/twisted/application/service.py", line 411, in loadApplication
    passphrase)
  File "/home/kippo/env/local/lib/python2.7/site-packages/twisted/persisted/sob.py", line 207, in loadValueFromFile
    eval(codeObj, d, d)
  File "kippo.tac", line 26, in <module>
    import kippo.core.auth
  File "/home/kippo/kippo/kippo/core/auth.py", line 102, in <module>
    class HoneypotPasswordChecker:
  File "/home/kippo/kippo/kippo/core/auth.py", line 106, in HoneypotPasswordChecker
    credentials.IPluggableAuthenticationModules)
exceptions.AttributeError: 'module' object has no attribute 'IPluggableAuthenticationModules'

Failed to load application: 'module' object has no attribute 'IPluggableAuthenticationModules'

Can anyone help me pls

**Comment by micheloosterhof** [comment]
You have a very recent version of Twisted, and IPluggableAuthenticationModules has been removed. You can try using an older version of Kippo. (Fixed in Cowrie, btw)

**Comment by Luegenbaron** [comment]
Thanks for reply
I will change to an older Version

**Comment by kamilsumairshaikh** [comment]
kippo@sshserver:~/kippo$ ./start.sh
twistd (the Twisted daemon) 16.0.0
Copyright (c) 2001-2016 Twisted Matrix Laboratories.
See LICENSE for details.
Starting kippo in the background...
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 617, in run
    runApp(config)
  File "/usr/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 348, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 413, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 424, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/application/service.py", line 411, in loadApplication
    passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 224, in loadValueFromFile
    eval(codeObj, d, d)
  File "kippo.tac", line 26, in <module>
    import kippo.core.auth
  File "/home/kippo/kippo/kippo/core/auth.py", line 102, in <module>
    class HoneypotPasswordChecker:
  File "/home/kippo/kippo/kippo/core/auth.py", line 106, in HoneypotPasswordChecker
    credentials.IPluggableAuthenticationModules)
exceptions.AttributeError: 'module' object has no attribute 'IPluggableAuthenticationModules'


Failed to load application: 'module' object has no attribute 'IPluggableAuthenticationModules'

Can someone help me with this? I have tried installing twisted version 15.0 but no luck

**Comment by desaster** [comment]
@kamilsumairshaikh please, if you are having the same issue with 15.0, can you share the error message you are getting with exactly that version. The last working twisted version is 15.1.0.

Please also make sure you are following the instructions: https://github.com/desaster/kippo/wiki/Running-Kippo

**Comment by kamilsumairshaikh** [comment]
@desaster I have tried with version 15.0 also but the result was the same. Btw thanks for another link +1:
