### ISSUE TITLE
Kippo is not starting

### ISSUE THREAD

**Issue by bentech4u** [desaster/kippo#200]
Hi 

i have pulled latest build , when i tried to start kippo, getting below error and it's not starting

`
[root@vps kippo]# ./start.sh

twistd (the Twisted daemon) 16.0.0

Copyright (c) 2001-2016 Twisted Matrix Laboratories.

See LICENSE for details.

Starting kippo in the background...

Unhandled Error

Traceback (most recent call last):

  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 617, in run

```
runApp(config)
```

  File "/usr/lib64/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp

```
_SomeApplicationRunner(config).run()
```

  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 348, in run

```
self.application = self.createOrGetApplication()
```

  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 413, in createOrGetApplication

```
application = getApplication(self.config, passphrase)
```

--- <exception caught here> ---

  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 424, in getApplication

```
application = service.loadApplication(filename, style, passphrase)
```

  File "/usr/lib64/python2.7/site-packages/twisted/application/service.py", line 411, in loadApplication

```
passphrase)
```

  File "/usr/lib64/python2.7/site-packages/twisted/persisted/sob.py", line 224, in loadValueFromFile

```
eval(codeObj, d, d)
```

  File "kippo.tac", line 15, in <module>

```
from twisted.conch.ssh import factory, keys
```

  File "/usr/lib64/python2.7/site-packages/twisted/conch/ssh/factory.py", line 16, in <module>

```
import transport, userauth, connection
```

  File "/usr/lib64/python2.7/site-packages/twisted/conch/ssh/transport.py", line 19, in <module>

```
from cryptography.exceptions import UnsupportedAlgorithm
```

exceptions.ImportError: No module named cryptography.exceptions

Failed to load application: No module named cryptography.exceptions

`

please anyone help me to fix this issue.

**Comment by p0si** [comment]
I'm also getting the same error ("Failed to load application: No module named cryptography.exceptions") and now I'm stuck... Any comments/ideas?

**Comment by mscox42** [comment]
I had the same issue with the cowrie fork. Fixed with install of cryptography module (pip install cryptography). You may need to resolve several dependencies for this as well (dev/devel packages for libffi, openssl, etc.). I think it's a difference with newer versions of twisted, but I'm not really sure.

**Comment by dstsmallbird** [comment]
Just found the solution on  CentOS 7: pip install twisted==15.2.0

**Comment by mchery** [comment]
For Ubuntu 16.04 server
# apt-get purge python-twisted
# apt-get install gcc
# cd /tmp
# wget https://twistedmatrix.com/Releases/Twisted/15.1/Twisted-15.1.0.tar.bz2
# tar xvf Twisted-15.1.0.tar.bz2
# reboot
# cd /tmp/Twisted-15.1.0
# chmod 777 INSTALL
# python setup.py install
and go to the kippo dir and start it.

**Comment by peter2233finn** [comment]
For Arch kippo is on the AUR.

**Comment by fgeek** [comment]
lol at chmod 777 INSTALL :)

**Comment by Raymond-Schooley** [comment]
Thank you for the instructions, I spent a lot of time trying to figure that out.

**Comment by desaster** [comment]
https://github.com/desaster/kippo/wiki/Running-Kippo
