### ISSUE TITLE
[Errno 13] Permission denied: 'data/ssh_host_rsa_key.pub'

### ISSUE THREAD

**Issue by FrostedKitten** [desaster/kippo#207]
Here` is my panel from start to finish.
I know it's a permission issue as stated by [this](https://github.com/desaster/kippo/issues/184) user saying "You have a permissions issue. The user under which you run kippo is not allowed to write to the file data/ssh_host_rsa_key.pub." But the thing is I'm not sure how to fix this.

could anyone lead me in the right direction. I saw what the other user stated saying he had to permit access to the folder, how can I do this?

```
kippo@raspberrypi:~/trunk $ ./start.sh
twistd (the Twisted daemon) 14.0.2
Copyright (c) 2001-2014 Twisted Matrix Laboratories.
See LICENSE for details.
Starting kippo in the background...
Generating new RSA keypair...
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/usr/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 441, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 452, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "kippo.tac", line 34, in <module>
    rsa_pubKeyString, rsa_privKeyString = core.ssh.getRSAKeys()
  File "/home/kippo/trunk/kippo/core/ssh.py", line 291, in getRSAKeys
    with file(public_key, 'w+b') as f:
exceptions.IOError: [Errno 13] Permission denied: 'data/ssh_host_rsa_key.pub'

Failed to load application: [Errno 13] Permission denied: 'data/ssh_host_rsa_key.pub'

```

**Comment by FrostedKitten** [comment]
Fixed. I used `sudo chmod -R 777 /home/kippo/trunk` while on my kippo user.

**Comment by Ameobea** [comment]
You should close the issue since it for one had nothing to do with the project and also was resolved, @FrostedKitten.
