### ISSUE TITLE
kippo on archlinux No module named kippo.core.config

### ISSUE THREAD

**Issue by sarcarx** [desaster/kippo#209]
I tried running kippo on archlinux, installed all dependencies.
The following error is displayed:

```
twistd (the Twisted daemon) 16.4.1
Copyright (c) 2001-2016 Twisted Matrix Laboratories.
See LICENSE for details.
Starting kippo in the background...
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/application/app.py", line 648, in run
    runApp(config)
  File "/usr/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.7/site-packages/twisted/application/app.py", line 379, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.7/site-packages/twisted/application/app.py", line 444, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/application/app.py", line 455, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python2.7/site-packages/twisted/application/service.py", line 411, in loadApplication
    passphrase)
  File "/usr/lib/python2.7/site-packages/twisted/persisted/sob.py", line 223, in loadValueFromFile
    eval(codeObj, d, d)
  File "kippo.tac", line 25, in <module>
    from kippo.core.config import config
exceptions.ImportError: No module named kippo.core.config


Failed to load application: No module named kippo.core.config
```
I did check the file in kippo/core/config.py does exist.
start.sh is being started by the user kippo

Any idea on how to solve the issue?

**Comment by sarcarx** [comment]
`pip2 install twisted==15.2.0`
fixed it.
Maybe we should modify the code to match with the newer versions.

**Comment by jingxa** [comment]
Thanks, i installed kippo-unbuntu ,but i have a error that no module kippo.core. finally i successed in running kippo by "pip2 install twisted==15.2.0"

**Comment by desaster** [comment]
db logging is broken with 15.2.0, so the last working version is 15.1.0.

https://github.com/desaster/kippo/wiki/Running-Kippo

**Comment by jingxa** [comment]
@desaster thanks .big man
