### ISSUE TITLE
I can't run the kippo honeypot I keep on getting errors even though I followed the installation 

### ISSUE THREAD

**Issue by artoev95** [desaster/kippo#215]
I get the following error when I try to run kippo .

Starting kippo in the background...
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/usr/local/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 441, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 452, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/service.py", line 403, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/local/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "kippo.tac", line 15, in <module>
    from twisted.conch.ssh import factory, keys
  File "/usr/local/lib/python2.7/dist-packages/twisted/conch/ssh/factory.py", line 15, in <module>
    import transport, userauth, connection
  File "/usr/local/lib/python2.7/dist-packages/twisted/conch/ssh/transport.py", line 22, in <module>
    from Crypto import Util
exceptions.ImportError: No module named Crypto

Failed to load application: No module named Crypto

**Comment by desaster** [comment]
No pycrypto installed? this doesn't look like a bug, so i'm closing it. Feel free to further reply here, though.

**Comment by artoev95** [comment]
I have to install pycrypto ?

**Comment by desaster** [comment]
Check the installation instructions here:

https://github.com/desaster/kippo/wiki/Running-Kippo

pycrypto is one of the packages installed inside the virtualenv.

**Comment by artoev95** [comment]
Ok thanks ,I will try again reinstalling the honeypot ,I was following a different method of installation from another website

**Comment by artoev95** [comment]
I get this error now about kippo tac ,but I have kippo.tac stored in my kippo folder
Unhandled Error
Traceback (most recent call last):
  File "/home/a/env/local/lib/python2.7/site-packages/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/home/a/env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/home/a/env/local/lib/python2.7/site-packages/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/home/a/env/local/lib/python2.7/site-packages/twisted/application/app.py", line 441, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/home/a/env/local/lib/python2.7/site-packages/twisted/application/app.py", line 452, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/home/a/env/local/lib/python2.7/site-packages/twisted/application/service.py", line 403, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/home/a/env/local/lib/python2.7/site-packages/twisted/persisted/sob.py", line 203, in loadValueFromFile
    fileObj = open(filename, mode)
exceptions.IOError: [Errno 2] No such file or directory: 'kippo.tac'

Failed to load application: [Errno 2] No such file or directory: 'kippo.tac'

**Comment by artoev95** [comment]
I get this error 
(env) a@a-VirtualBox:~/kippo$ twistd -n -y kippo.tac
ERROR: kippo.cfg is missing!

But I have kippo.cfg file inside the kippo folder

**Comment by artoev95** [comment]
Fixed that problem with this line  cp kippo.cfg.dist kippo.cfg
