### ISSUE TITLE
failed to start kippo - No module named conch.ssh

### ISSUE THREAD

**Issue by urbinek** [desaster/kippo#219]
Hello there!

I have some wierd issues with running Kippo on CentOS7
```
urbinek@honeypot kippo-master $ twistd -y kippo.tac -l log/kippo.log --pidfile kippo.pid
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 652, in run
    runApp(config)
  File "/usr/lib64/python2.7/site-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 386, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 451, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 462, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib64/python2.7/site-packages/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib64/python2.7/site-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "kippo.tac", line 15, in <module>
    from twisted.conch.ssh import factory, keys
exceptions.ImportError: No module named conch.ssh

Failed to load application: No module named conch.ssh
```

whoever module itself seems to be ok
```
urbinek@honeypot kippo-master $ python -c 'import Crypto'
urbinek@honeypot kippo-master $
```

any idea how to bite this?

**Comment by desaster** [comment]
check out the instructions in the wiki https://github.com/desaster/kippo/wiki/Running-Kippo
