### ISSUE TITLE
Kippo error connection lost - bad packet length

### ISSUE THREAD

**Issue by Locmap99** [desaster/kippo#231]
Hello all,

I'm building Kippo Honeypot, but I have a problem **connection lost** when I access Kippo via SSH and **bad packet length** error when I access Kippo via Telnet.

Logging displays when I access Kippo via SSH.
[-] twistd 15.2.0 (/usr/bin/python 2.7.14) starting up.
 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
 [-] HoneyPotSSHFactory starting on 2555
 [-] Starting factory <kippo.core.ssh.HoneyPotSSHFactory instance at 0x7f6b9e1783b0>
 [-] New connection: yy.yy.yy.yy:55470 (xx.xx.xx.xx:2555) [session: 0]
 [-] Remote SSH version: SSH-2.0-OpenSSH_7.4
 [HoneyPotTransport,0,xx.xx.xx.xx] kex alg, key alg: diffie-hellman-group-exchange-sha1 ssh-rsa
 [HoneyPotTransport,0,xx.xx.xx.xx] outgoing: aes128-ctr hmac-sha1 none
 [HoneyPotTransport,0,xx.xx.xx.xx] incoming: aes128-ctr hmac-sha1 none
 [HoneyPotTransport,0,xx.xx.xx.xx] Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 102, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 85, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 611, in _doReadOrWrite
            why = selectable.doRead()
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 209, in doRead
            return self._dataReceived(data)
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 215, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/Honey/kippo/kippo/core/ssh.py", line 170, in dataReceived
            transport.SSHServerTransport.dataReceived(self, data)
          File "/usr/local/lib/python2.7/dist-packages/twisted/conch/ssh/transport.py", line 461, in dataReceived
            self.dispatchMessage(messageNum, packet[1:])
          File "/usr/local/lib/python2.7/dist-packages/twisted/conch/ssh/transport.py", line 476, in dispatchMessage
            f(payload)
          File "/usr/local/lib/python2.7/dist-packages/twisted/conch/ssh/transport.py", line 1038, in ssh_KEX_DH_GEX_INIT
            self._keySetup(sharedSecret, exchangeHash)
          File "/usr/local/lib/python2.7/dist-packages/twisted/conch/ssh/transport.py", line 756, in _keySetup
            outs[2], ins[2])
          File "/usr/local/lib/python2.7/dist-packages/twisted/conch/ssh/transport.py", line 1430, in setKeys
            o = self._getCipher(self.outCipType, outIV, outKey)
          File "/usr/local/lib/python2.7/dist-packages/twisted/conch/ssh/transport.py", line 1456, in _getCipher
            counter=_Counter(iv, mod.block_size))
          File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/AES.py", line 94, in new
            return AESCipher(key, *args, **kwargs)
          File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/AES.py", line 59, in __init__
            blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
          File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
            self._cipher = factory.new(key, *args, **kwargs)
        exceptions.ValueError: CTR mode needs counter parameter, not IV
 [HoneyPotTransport,0,xx.xx.xx.xx] connection lost

I appreciate any your idea... 
Thank you so much

**Comment by Locmap99** [comment]
Hello,
Please help me!!!

**Comment by gdzjzhang** [comment]
hello
mabey you nedd install 2.6.0 pycrypto
pip install pycrypto==2.6.0
