### ISSUE TITLE
error after run the command ./start.sh

### ISSUE THREAD

**Issue by xxxzahirxxx** [desaster/kippo#233]
guys. i have error after i run this command ./start.sh

twistd (the Twisted daemon) 16.0.0
Copyright (c) 2001-2016 Twisted Matrix Laboratories.
See LICENSE for details.
Starting kippo in the background...
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 617, in run
    runApp(config)
  File "/usr/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 348, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 413, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 424, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/application/service.py", line 411, in loadApplication
    passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 224, in loadValueFromFile
    eval(codeObj, d, d)
  File "kippo.tac", line 26, in <module>
    import kippo.core.auth
  File "/home/kippo/kippo/kippo/core/auth.py", line 102, in <module>
    class HoneypotPasswordChecker:
  File "/home/kippo/kippo/kippo/core/auth.py", line 106, in HoneypotPasswordChecker
    credentials.IPluggableAuthenticationModules)
exceptions.AttributeError: 'module' object has no attribute 'IPluggableAuthenticationModules'

Failed to load application: 'module' object has no attribute 'IPluggableAuthenticationModules'

Currently I'm using Ubuntu 16.04.4 LTS

**Comment by desaster** [comment]
See:
* https://github.com/desaster/kippo/issues/191
* https://github.com/desaster/kippo/wiki/Running-Kippo

**Comment by xxxzahirxxx** [comment]
I get this error 

(env) kippo@ubuntu:~$ twistd -n -y kippo.tac
Unhandled Error
Traceback (most recent call last):
  File "/home/kippo/env/local/lib/python2.7/site-packages/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/home/kippo/env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/home/kippo/env/local/lib/python2.7/site-packages/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/home/kippo/env/local/lib/python2.7/site-packages/twisted/application/app.py", line 441, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/home/kippo/env/local/lib/python2.7/site-packages/twisted/application/app.py", line 452, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/home/kippo/env/local/lib/python2.7/site-packages/twisted/application/service.py", line 403, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/home/kippo/env/local/lib/python2.7/site-packages/twisted/persisted/sob.py", line 203, in loadValueFromFile
    fileObj = open(filename, mode)
exceptions.IOError: [Errno 2] No such file or directory: 'kippo.tac'

Failed to load application: [Errno 2] No such file or directory: 'kippo.tac'

**Comment by desaster** [comment]
looks like you are trying to run kippo.tac in a directory where there is no kippo.tac

**Comment by xxxzahirxxx** [comment]
what is the right command to run it?

**Comment by desaster** [comment]
The command is right, you're just running it in a wrong directory.

I'm sorry to point this out, but this is rather basic operating system stuff. I do not recommend that you run honeypots outside your local environment, and never expose it to the internet. Since this is security related stuff, a high level of technical expertise is a requirement, otherwise your honeypot may do more harm than good.

**Comment by xxxzahirxxx** [comment]
Ok noted. Thanks for your advice.
