### ISSUE TITLE
start.sh not start

### ISSUE THREAD

**Issue by maxitis92** [desaster/kippo#237]
After run ./start.sh

i have a problem. Not start the ./start.sh

What is the problem?

Thanks advanced

marios@marios:~$ cd kippo/
marios@marios:~/kippo$ ./start.sh
twistd (the Twisted daemon) 18.7.0
Copyright (c) 2001-2018 Twisted Matrix Laboratories.
See LICENSE for details.
Starting kippo in the background...
Unhandled Error
Traceback (most recent call last):
  File "/home/marios/.local/lib/python2.7/site-packages/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/home/marios/.local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/home/marios/.local/lib/python2.7/site-packages/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/home/marios/.local/lib/python2.7/site-packages/twisted/application/app.py", line 453, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/home/marios/.local/lib/python2.7/site-packages/twisted/application/app.py", line 464, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/home/marios/.local/lib/python2.7/site-packages/twisted/application/service.py", line 416, in loadApplication
    application = sob.loadValueFromFile(filename, 'application')
  File "/home/marios/.local/lib/python2.7/site-packages/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "kippo.tac", line 25, in <module>
    from kippo.core.config import config
exceptions.ImportError: No module named kippo.core.config

Failed to load application: No module named kippo.core.config

**Comment by linuxthefish** [comment]
I also had this issue, you need to run https://github.com/desaster/kippo/wiki/Running-Kippo
