### ISSUE TITLE
module 'twisted.cred.credentials' has no attribute 'IPluggableAuthenticationModules'

### ISSUE THREAD

**Issue by benny12312311** [desaster/kippo#239]
when I followed the procedure in https://github.com/desaster/kippo/wiki/Running-Kippo
I have this problem

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/usr/lib/python3/dist-packages/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/usr/lib/python3/dist-packages/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python3/dist-packages/twisted/application/app.py", line 453, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib/python3/dist-packages/twisted/application/app.py", line 464, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python3/dist-packages/twisted/application/service.py", line 416, in loadApplication
    application = sob.loadValueFromFile(filename, 'application')
  File "/usr/lib/python3/dist-packages/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "kippo.tac", line 22, in <module>
    from kippo.core.auth import auth
  File "/home/kippo/kippo/kippo/core/auth.py", line 103, in <module>
    class HoneypotPasswordChecker:
  File "/home/kippo/kippo/kippo/core/auth.py", line 105, in HoneypotPasswordChecker
    credentials.IPluggableAuthenticationModules)
builtins.AttributeError: module 'twisted.cred.credentials' has no attribute 'IPluggableAuthenticationModules'

Failed to load application: module 'twisted.cred.credentials' has no attribute 'IPluggableAuthenticationModules'

Please help me!! #

**Comment by desaster** [comment]
Please can you clarify that you are running a version of twisted that still works with kippo:

```
% twistd --version
twistd (the Twisted daemon) 15.1.0
Copyright (c) 2001-2015 Twisted Matrix Laboratories.
See LICENSE for details.
```

**Comment by desaster** [comment]
Looks like you are running python3 and not running a virtualev.

Kippo is old software, and requires older python and twisted to get it running. It's also not up-to-date with the SSH protocol today, so don't expect to get a good honeypot experience from it.

**Comment by benny12312311** [comment]
I'm running a virtualenv
but when I use twistd --version
it goes out

`$  twistd --version

Command 'twistd' not found, did you mean:

  command 'twist' from snap twist (0.3.0)
  command 'twistd3' from deb python3-twisted (18.9.0-11ubuntu0.20.04.1)
  command 'twist3' from deb python3-twisted (18.9.0-11ubuntu0.20.04.1)

See 'snap info <snapname>' for additional versions.`

**Comment by benny12312311** [comment]
I'm running a virtualenv
but when I use twistd --version
it goes out

`
$ twistd --version

Command 'twistd' not found, did you mean:

command 'twist' from snap twist (0.3.0)
command 'twistd3' from deb python3-twisted (18.9.0-11ubuntu0.20.04.1)
command 'twist3' from deb python3-twisted (18.9.0-11ubuntu0.20.04.1)

See 'snap info ' for additional versions.
`

**Comment by benny12312311** [comment]
I'm running a virtualenv
but when I use twistd --version
it goes out

```
$ twistd --version

Command 'twistd' not found, did you mean:

command 'twist' from snap twist (0.3.0)
command 'twistd3' from deb python3-twisted (18.9.0-11ubuntu0.20.04.1)
command 'twist3' from deb python3-twisted (18.9.0-11ubuntu0.20.04.1)

See 'snap info ' for additional versions.
```
