### ISSUE TITLE
python-wokkel API changed?

### ISSUE THREAD

**Issue by ghost** [desaster/kippo#53]
_From [google-code@jensdiemer.de](https://code.google.com/u/110247016830768358875/) on July 04, 2012 14:12:29_

I tried to enable database_xmpp and get this traceback:

```
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 705, in doRead
        protocol.makeConnection(transport)
      File "/usr/lib/python2.7/dist-packages/twisted/internet/protocol.py", line 462, in makeConnection
        self.connectionMade()
      File "/home/kippo/kippo/kippo/core/honeypot.py", line 504, in connectionMade
        self.transport.sessionno)
      File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 594, in write
        msg(message, printed=1, isError=self.isError)
    --- <exception caught here> ---
      File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 284, in msg
        self.observers[i](actualEventDict)
      File "/home/kippo/kippo/kippo/core/dblog.py", line 71, in emit
        match.groups()[2], int(match.groups()[3]))
      File "/home/kippo/kippo/kippo/dblog/xmpp.py", line 117, in createSession
        self.broadcast('createsession', ses)
      File "/home/kippo/kippo/kippo/dblog/xmpp.py", line 93, in broadcast
        (self.signals[msgtype], self.muc.server) , msg)
      File "/home/kippo/kippo/kippo/dblog/xmpp.py", line 102, in report
        self.muc.groupChat(to,  None, children=[body])
    exceptions.TypeError: groupChat() got an unexpected keyword argument 'children'
```

Seems that the python-wokkel api has been changed?

_Original issue: http://code.google.com/p/kippo/issues/detail?id=53_

**Comment by desaster** [comment]
Note that the xmpp implementation uses a modified version of wokkel.

Here's a gist on how install it along with kippo:
https://gist.github.com/desaster/6c5bbf30b43f797a5e1a

I haven't used the xmpp myself much after the initial tests. Someone really should look into rewriting/updating the code.
